CREATE TABLE ATIVIDADE(
id INT PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR (100) NOT NULL,
situacao INT NOT NULL DEFAULT 0 
);

INSERT INTO ATIVIDADE (titulo) values (@titulo);

UPDATE ATIVIDADE SET situacao =@situacao WHERE id = @id;

SELECT * FROM ATIVIDADE WHERE situacao = 1;

SELECT * FROM ATIVIDADE WHERE situacao = 0;